version: '3'

services:
  corporate:
    image: 'corporate:latest'
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - corporate_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://corporate_db:5432/corporate
      - SPRING_DATASOURCE_USERNAME=corporate
      - SPRING_DATASOURCE_PASSWORD=corporate
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  corporate_db:
    image: postgres:12.2
    environment:
      - POSTGRES_USER=corporate
      - POSTGRES_PASSWORD=corporate