version: '3'

services:
  corporate:
    image: 'corporate:latest'
    build:
      context: .
    container_name: corporate
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/corporate
      - SPRING_DATASOURCE_USERNAME=corporate
      - SPRING_DATASOURCE_PASSWORD=corporate
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=corporate
      - POSTGRES_PASSWORD=corporate